MOVING INTO HOME DIR
SGE_TASK_ID: 4
Fri Apr  5 13:18:04 EDT 2019
/opt/sge/default/spool/compute-0-8/job_scripts/5109577: line 30: print: command not found
Running classification on subject number 106
/data/jag/cnds/amennen/miniconda3/envs/rtAtten/lib/python3.6/site-packages/sklearn/linear_model/sag.py:326: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  "the coef_ did not converge", ConvergenceWarning)
106
0
1
2
3
4
5
6
Traceback (most recent call last):
  File "anne_additions/run_train_test.py", line 28, in <module>
    train_test_python_classifier(subjectNum)
  File "/data/jag/cnds/amennen/brainiak/rtAttenPenn_cloud/anne_additions/getcs.py", line 140, in train_test_python_classifier
    pyModel_test = utils.loadMatFile(pyModelFn)
  File "/data/jag/cnds/amennen/brainiak/rtAttenPenn_cloud/rtfMRI/utils.py", line 25, in loadMatFile
    if not os.path.isfile(filename):
  File "/data/jag/cnds/amennen/miniconda3/envs/rtAtten/lib/python3.6/genericpath.py", line 30, in isfile
    st = os.stat(path)
TypeError: stat: path should be string, bytes, os.PathLike or integer, not NoneType
Finished running classification on subject number 106
Fri Apr  5 13:35:53 EDT 2019
